// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7ZTBpmX2y_DdJllNfyhnQtPUoKQUvEdM',
    appId: '1:128058390693:web:60a0f92fa78422e242354c',
    messagingSenderId: '128058390693',
    projectId: 'constructionproj',
    authDomain: 'constructionproj.firebaseapp.com',
    storageBucket: 'constructionproj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPC6rY1bvZ0yjSP1RdaWNz1Qgk6rhMjkg',
    appId: '1:128058390693:android:be914b9aee9e57d842354c',
    messagingSenderId: '128058390693',
    projectId: 'constructionproj',
    storageBucket: 'constructionproj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYFjk9rKa7BDtcP20riSY6ksuZhH4BB4A',
    appId: '1:128058390693:ios:35767560b84e9e9242354c',
    messagingSenderId: '128058390693',
    projectId: 'constructionproj',
    storageBucket: 'constructionproj.appspot.com',
    iosClientId: '128058390693-m45av7kkmkb9cqhq35tei89qsijfrn3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.construction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYFjk9rKa7BDtcP20riSY6ksuZhH4BB4A',
    appId: '1:128058390693:ios:35767560b84e9e9242354c',
    messagingSenderId: '128058390693',
    projectId: 'constructionproj',
    storageBucket: 'constructionproj.appspot.com',
    iosClientId: '128058390693-m45av7kkmkb9cqhq35tei89qsijfrn3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.construction',
  );
}
